language: go

go:
  - 1.5
  - 1.6
  - tip

install:
  - "git clone git@github.com:kayatra/helpers.git ${GOPATH}/helpers"
  - "${GOPATH}/helpers/scripts/glide-setup.sh"

allow_failures:
  - go: tip

script:
  - "${GOPATH}/helpers/scripts/go-test.sh"

env:
  - "GO15VENDOREXPERIMENT=1"
